# Site settings
title: Chickadee Perch LLC
email:
description: Affordable housing in Bulter, PA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chickadeeperch.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
